name: CD

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[cd skip]')"

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Format check
        run: deno fmt --check

      - name: Lint check
        run: deno lint

      - name: Type Check
        run: deno task check:types

      - name: Test
        run: deno task test

      - name: Build
        run: deno task build:npm ${{ github.ref_name }}

      - name: Publish to jsr
        run: npx jsr publish

      #- name: Publish to npm
      #  env:
      #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #  run: cd npm && npm publish --access public
