name: Release CD

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[cd skip]')"

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format check
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test -A

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        run: deno run -A ./scripts/build_npm.ts ${{ github.ref_name }}

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd npm && npm publish
